#const Deck = ["INVESTORS","RETREAT"] #Debug hand for testing

#Cards : ["INVESTORS","RETREAT","ADS","TAX_FRAUD","LOWER_PRICES","FAKE_NEWS","SELL_STOCKS",
#		"HIRING_CAMPAIGN","CORPORATE_SPYING","LAYOFFS","OUTSOURCING"]

const Deck = ["INVESTORS", "INVESTORS", "INVESTORS", "RETREAT", "RETREAT", 
	"RETREAT", "ADS", "ADS", "TAX_FRAUD", "LOWER_PRICES", "LOWER_PRICES", 
	"FAKE_NEWS", "SELL_STOCKS", "HIRING_CAMPAIGN", "HIRING_CAMPAIGN", 
	"LAYOFFS", "LAYOFFS", "OUTSOURCING", "TEAM_COHESION", "TEAM_COHESION"]
