#const Deck = ["INVESTORS","RETREAT"] #Debug hand for testing

#Cards : ["INVESTORS","RETREAT","ADS","TAX_FRAUD","LOWER_PRICES","FAKE_NEWS","SELL_STOCKS",
#		"HIRING_CAMPAIGN","CORPORATE_SPYING","LAYOFFS","OUTSOURCING"]

const Deck = ["ADS", "ADS", "ADS", "SUBCONTRACT", "SUBCONTRACT", "SUBCONTRACT", 
	"EXPAND", "OUTSOURCING", "FAKE_NEWS", "UNPAID_HOURS", "TEAM_COHESION", "TEAM_COHESION",
	"TEAM_COHESION", "INVESTORS", "INVESTORS", "INVESTORS", "LOWER_PRICES", "LOWER_PRICES",
	"LAYOFFS", "HIRING_CAMPAIGN", "CRUNCH", "CRUNCH"]
