#const Deck = ["INVESTORS","RETREAT"] #Debug hand for testing

#Cards : ["INVESTORS","RETREAT","ADS","TAX_FRAUD","LOWER_PRICES","FAKE_NEWS","SELL_STOCKS",
#		"HIRING_CAMPAIGN","CORPORATE_SPYING","LAYOFFS","OUTSOURCING"]

const Deck = ["ADS", "SUBCONTRACT","FAKE_NEWS", "UNPAID_HOURS", "TEAM_COHESION",
	"INVESTORS", "LOWER_PRICES",
	"LAYOFFS", "HIRING_CAMPAIGN", "CRUNCH"]
